"""empty message

Revision ID: 1c4aeae36c1d
Revises: 43617d4ed344
Create Date: 2022-10-28 09:38:50.231952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4aeae36c1d'
down_revision = '43617d4ed344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('isthumb', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_article.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_viewed')
    # ### end Alembic commands ###
