"""empty message

Revision ID: 316e82a19f02
Revises: 1c4aeae36c1d
Create Date: 2022-10-28 09:54:46.669969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '316e82a19f02'
down_revision = '1c4aeae36c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_viewed', sa.Column('isviewed', sa.Boolean(), nullable=True))
    op.drop_column('t_viewed', 'isthumb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_viewed', sa.Column('isthumb', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('t_viewed', 'isviewed')
    # ### end Alembic commands ###
