"""empty message

Revision ID: 43617d4ed344
Revises: 523885d224e7
Create Date: 2022-10-28 08:52:04.866025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43617d4ed344'
down_revision = '523885d224e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_thumb', sa.Column('isthumb', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_thumb', 'isthumb')
    # ### end Alembic commands ###
