"""empty message

Revision ID: 45ef7ba11d6b
Revises: 6d7da44aeaa9
Create Date: 2022-10-22 12:01:06.696914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45ef7ba11d6b'
down_revision = '6d7da44aeaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 't_user', ['uid'], ['uid'])
    op.drop_constraint('t_article_ibfk_1', 't_article', type_='foreignkey')
    op.create_foreign_key(None, 't_article', 't_user', ['pid'], ['uid'])
    op.add_column('t_user', sa.Column('uid', sa.Integer(), nullable=False))
    op.drop_column('t_user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('t_user', 'uid')
    op.drop_constraint(None, 't_article', type_='foreignkey')
    op.create_foreign_key('t_article_ibfk_1', 't_article', 't_user', ['pid'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 't_user', ['uid'], ['id'])
    # ### end Alembic commands ###
