"""empty message

Revision ID: 523885d224e7
Revises: 6b1e1be789d1
Create Date: 2022-10-27 20:46:52.566602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523885d224e7'
down_revision = '6b1e1be789d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_thumb_ibfk_2', 't_thumb', type_='foreignkey')
    op.drop_constraint('t_thumb_ibfk_1', 't_thumb', type_='foreignkey')
    op.create_foreign_key(None, 't_thumb', 't_article', ['aid'], ['id'])
    op.create_foreign_key(None, 't_thumb', 't_user', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_thumb', type_='foreignkey')
    op.drop_constraint(None, 't_thumb', type_='foreignkey')
    op.create_foreign_key('t_thumb_ibfk_1', 't_thumb', 't_user', ['aid'], ['id'])
    op.create_foreign_key('t_thumb_ibfk_2', 't_thumb', 't_article', ['uid'], ['id'])
    # ### end Alembic commands ###
