"""empty message

Revision ID: 5552f9cba092
Revises: 7268c95327a5
Create Date: 2022-10-19 14:05:41.500499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5552f9cba092'
down_revision = '7268c95327a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 't_user', ['uid'], ['id'])
    op.drop_column('comments', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_2', 'comments', 't_user', ['user'], ['id'])
    op.drop_column('comments', 'uid')
    # ### end Alembic commands ###
