"""empty message

Revision ID: 6b1e1be789d1
Revises: b5580bd4a9f3
Create Date: 2022-10-27 20:30:33.920162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1e1be789d1'
down_revision = 'b5580bd4a9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_thumb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['t_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_thumb')
    # ### end Alembic commands ###
