"""empty message

Revision ID: 6d7da44aeaa9
Revises: 5552f9cba092
Create Date: 2022-10-21 22:35:46.904290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7da44aeaa9'
down_revision = '5552f9cba092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_user_ibfk_1', 't_user', type_='foreignkey')
    op.create_foreign_key(None, 't_user', 't_role', ['rid'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    op.create_foreign_key('t_user_ibfk_1', 't_user', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###
