"""empty message

Revision ID: 7268c95327a5
Revises: 82e1250271b0
Create Date: 2022-10-19 13:36:18.757950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7268c95327a5'
down_revision = '82e1250271b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 't_user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user')
    # ### end Alembic commands ###
