"""empty message

Revision ID: 748bd3062da2
Revises: 9ec4a1dcafd0
Create Date: 2022-10-17 08:51:33.740372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748bd3062da2'
down_revision = '9ec4a1dcafd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('avatar_url', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'avatar_url')
    # ### end Alembic commands ###
