"""empty message

Revision ID: b5580bd4a9f3
Revises: c04190c47579
Create Date: 2022-10-25 20:56:56.791057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5580bd4a9f3'
down_revision = 'c04190c47579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 't_wxuser', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_wxuser', type_='unique')
    # ### end Alembic commands ###
