"""empty message

Revision ID: c04190c47579
Revises: e602355cc816
Create Date: 2022-10-25 20:44:30.901541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04190c47579'
down_revision = 'e602355cc816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_wxuser', sa.Column('wxid', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_wxuser', 'wxid')
    # ### end Alembic commands ###
